#!/bin/sh

##############################################################################
##
##  Gradle start up script for POSIX generated by Gradle.
##
##############################################################################

# Set local variables
APP_HOME="$(cd "$(dirname "$0")" && pwd)"
APP_NAME="Gradle"
APP_BASE_NAME=${0##*/}

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='-Xmx64m -Xms64m'

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD="maximum"

warn () {
  echo "$*"
}

die () {
  echo
  echo "$*"
  echo
  exit 1
}

# OS specific support functions.
# shellcheck disable=SC2039
cygwin=false
msys=false
darwin=false
case "$(uname)" in
  CYGWIN* ) cygwin=true ;;
  Darwin* ) darwin=true ;;
  MSYS* | MINGW* ) msys=true ;;
  * ) ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

# Determine the Java command to use.
if [ -n "$JAVA_HOME" ] ; then
  if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
    # IBM's JDK on AIX uses strange locations for the executables
    JAVACMD="$JAVA_HOME/jre/sh/java"
  else
    JAVACMD="$JAVA_HOME/bin/java"
  fi
  if [ ! -x "$JAVACMD" ] ; then
    die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME"
  fi
else
  JAVACMD="java"
fi

if [ ! -x "$JAVACMD" ] ; then
  die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH."
fi

# Increase the maximum file descriptors if possible.
if [ "$cygwin" = false ] && [ "$darwin" = false ] && [ "$msys" = false ]; then
  case $MAX_FD in
    max*)
      MAX_FD=$(ulimit -H -n) || warn "Could not query maximum file descriptor limit"
    ;;
    '' | soft)
      MAX_FD=$(ulimit -S -n) || warn "Could not query soft file descriptor limit"
    ;;
  esac
  if [ "$MAX_FD" != "unlimited" ]; then
    ulimit -n "$MAX_FD" || warn "Could not set file descriptor limit"
  fi
fi

# For Darwin, use the default macOS user dir
if [ "$darwin" = true ] ; then
  if [ -z "$JAVA_HOME" ]; then
    if [ -x "/usr/libexec/java_home" ]; then
      JAVA_HOME=$( /usr/libexec/java_home )
      export JAVA_HOME
    fi
  fi
fi

# For Cygwin or MSYS, ensure paths are in UNIX format before running java
if [ "$cygwin" = true ] || [ "$msys" = true ] ; then
  APP_HOME=$( cygpath --unix "$APP_HOME" )
  CLASSPATH=$( cygpath --path --unix "$CLASSPATH" )
  JAVACMD=$( cygpath --unix "$JAVACMD" )
fi

exec "$JAVACMD" $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS \
  -Dorg.gradle.appname="$APP_BASE_NAME" \
  -classpath "$CLASSPATH" \
  org.gradle.wrapper.GradleWrapperMain "$@"
